export const GET_ALL_ITEMS= 'GET_ALL_ITEMS';
export const ADD_NEW_ITEM ='ADD_NEW_ITEM';
export const GET_ONE_ITEM ='GET_ONE_ITEM';
export const GET_ALL_ITEMS_FROM_ONE_USER ='GET_ALL_ITEMS_FROM_ONE_USER';
export const GET_ALL_ITEMS_FROM_CATEGORIE ='GET_ALL_ITEMS_FROM_CATEGORIE';
export const TRIE_FROM_PRIX='TRIE_FROM_PRIX';
export const EFFACER_UN_ARTICLE ='EFFACER_UN_ARTICLE';
export const EFFACER_USER='EFFACER_USER';
export const CREATE_USER='CREATE_USER';


